plugins { id 'com.android.application' }

android {
    namespace 'com.chalshdana.app'
    compileSdk 35

    signingConfigs {
        release {
            def bundledKs = file("${rootProject.projectDir}/dana-signing.jks")
            storeFile bundledKs
            storePassword "dana12345"
            keyAlias "dana"
            keyPassword "dana12345"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId 'com.chalshdana.app'
        minSdk 23
        targetSdk 35
        versionCode 5
        versionName '1.4'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
