package com.chalshdana.app;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root; TextView question, progress, coins; int index=0, score=0, coin=50;
    String[][] qs={{"پایتخت فرانسه کدام است؟","پاریس","رم","برلین","مادرید","0"},{"بزرگ‌ترین سیاره منظومه شمسی کدام است؟","مشتری","زمین","مریخ","زهره","0"},{"بلندترین کوه جهان کدام است؟","اورست","دماوند","کی۲","آلپ","0"},{"آب از چه عناصری تشکیل شده است؟","هیدروژن و اکسیژن","کربن و اکسیژن","نیتروژن و هیدروژن","آهن و اکسیژن","0"},{"نویسنده شاهنامه چه کسی است؟","فردوسی","حافظ","سعدی","مولوی","0"}};
    @Override public void onCreate(Bundle b){super.onCreate(b); showHome();}
    TextView t(String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(Color.WHITE);v.setGravity(Gravity.CENTER);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setPadding(12,12,12,12);return v;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(17);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackgroundColor(Color.rgb(23,105,224));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,58);p.setMargins(16,8,16,8);b.setLayoutParams(p);return b;}
    void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER_HORIZONTAL);root.setPadding(18,25,18,18);root.setBackgroundColor(Color.rgb(7,26,61));setContentView(root);}
    void showHome(){base(); TextView logo=t("💡  چالش دانا",34);root.addView(logo,new LinearLayout.LayoutParams(-1,100)); TextView sub=t("بازی اطلاعات عمومی",18);root.addView(sub); Button start=btn("▶  شروع بازی");start.setBackgroundColor(Color.rgb(255,160,0));start.setOnClickListener(v->startGame());root.addView(start);Button daily=btn("🔥  چالش روزانه");daily.setOnClickListener(v->startGame());root.addView(daily);Button cats=btn("📚  دسته‌بندی‌ها");cats.setOnClickListener(v->Toast.makeText(this,"جهان • ایران • تاریخ • علم • فضا • ورزش • سرگرمی",Toast.LENGTH_LONG).show());root.addView(cats);Button profile=btn("🏆  رکورد من");profile.setOnClickListener(v->Toast.makeText(this,"امتیاز این نسخه: "+score,Toast.LENGTH_SHORT).show());root.addView(profile);}
    void startGame(){index=0;score=0;coin=50;showQuestion();}
    void showQuestion(){base(); LinearLayout.LayoutParams wrap=new LinearLayout.LayoutParams(-1,-2);coins=t("🪙 "+coin,18);coins.setGravity(Gravity.RIGHT);root.addView(coins,wrap);progress=t("سؤال "+(index+1)+" از "+qs.length,17);root.addView(progress);question=t(qs[index][0],22);question.setBackgroundColor(Color.WHITE);question.setTextColor(Color.rgb(7,26,61));root.addView(question,new LinearLayout.LayoutParams(-1,150));String[] opts={qs[index][1],qs[index][2],qs[index][3],qs[index][4]};for(int i=0;i<4;i++){final int n=i;Button b=btn((char)('A'+i)+"  "+opts[i]);b.setBackgroundColor(Color.rgb(23,105,224));b.setOnClickListener(v->answer(n,b));root.addView(b);} }
    void answer(int n,Button b){if(n==Integer.parseInt(qs[index][5])){score+=10;coin+=5;b.setBackgroundColor(Color.rgb(20,170,90));Toast.makeText(this,"✅ پاسخ درست! +10 امتیاز",Toast.LENGTH_SHORT).show();}else{coin=Math.max(0,coin-5);b.setBackgroundColor(Color.rgb(190,50,60));Toast.makeText(this,"❌ پاسخ نادرست",Toast.LENGTH_SHORT).show();}index++;new Handler().postDelayed(()->{if(index<qs.length)showQuestion();else showResult();},650);}
    void showResult(){base();root.addView(t("🏆 پایان بازی",30));root.addView(t("امتیاز شما: "+score,25));root.addView(t("سکه: "+coin,20));Button again=btn("🔄 دوباره بازی کن");again.setOnClickListener(v->startGame());root.addView(again);Button home=btn("⌂ بازگشت به خانه");home.setOnClickListener(v->showHome());root.addView(home);}
}
